### ISSUE TITLE
Solution for issue

### ISSUE THREAD

**Issue by SaiUpadhyayula** [SergioRuyDev/PersonalBlog#1]
https://github.com/SergioRuyDev/PersonalBlog/blob/05055db545c71272e3f7cbbf6980ae46ab06b629/src/main/java/com/sergioruy/personalblog/security/PostService.java#L36

    private PostDto mapFromPostToDto(Post post) {
        PostDto postDto = new PostDto();
        postDto.setId(postDto.getId());
        postDto.setTitle(postDto.getTitle());
        postDto.setContent(postDto.getContent());
        postDto.setUsername(postDto.getUsername());
        return postDto;
    }

should be 

    private PostDto mapFromPostToDto(Post post) {
        PostDto postDto = new PostDto();
        postDto.setId(post.getId());
        postDto.setTitle(post.getTitle());
        postDto.setContent(post.getContent());
        postDto.setUsername(post.getUsername());
        return postDto;
    }

**Comment by SergioRuyDev** [comment]
Thanks man, the issue was solved.
